import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { LogBox } from 'react-native';

import { UserProvider } from './src/context/UserContext';
import { FirebaseProvider } from './src/context/FirebaseContext';

import AppStackScreens from './src/stacks/AppStackScreens';

// This LogBox method suppresses the warning generated by the Flatlist on the Home and Favoirtes screens. Despite using the provided keyExtractor prop and verifying through console logs that each item in the list DOES have the correct key, it still throws the error.
LogBox.ignoreLogs(['Each child']);

export default App = () => {
  return (
    <FirebaseProvider>
      <UserProvider>
        <NavigationContainer>
          <AppStackScreens />
        </NavigationContainer>
      </UserProvider>
    </FirebaseProvider>
  );
};
